Numpy broadcasting in python

A sensible way of doing elementwise operations on arrays of different(but compatible) shapes.

It works with plus, minus, times, exponentiation, min/max, and many more elementwise operations.

Shape Compatibility Rules:

1.If x,y have a different number of dimensions, prepend 1's to the shape of the shorter.
2.Any axis of length 1 can be repeated(broadcast) to the length of the other vector's length in the axis.
3.All other axes must have matching lengths.

If the above three conditions are satisfied then we can get broadcasted shape.  

# Example 1

x.shape == ( 2, 3 )

y.shape == ( 2, 3 ) # compatible
y.shape == ( 2, 1 ) # compatible
y.shape == ( 1, 3 ) # compatible
y.shape == ( 3, ) #(1, 3) compatible

#NOT compatibles

y.shape == ( 3, 2 ) # NOT compatible
y.shape == ( 2, ) # (1, 2) NOT compatible

In [11]:
# Examples
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.shape)
print(b.shape)
print(a + b)

(4,)
(4,)
[2 4 6 8]


In [14]:
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])

print(a.shape)
print(a)
print()
print(b.shape)
print(b)
print()
print(a + b)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(a)

b = np.array([1,2,3])
print(b.shape)
print(b)

c = np.array([10,20])
print(c.shape)
print(c)

#print(a + b) #can't broadcast since (3,2) and (1,3) are incompatible shapes
print("Addition of a and c")
print(a + c)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3,)
[1 2 3]
(2,)
[10 20]
Addition of a and c
[[11 22]
 [13 24]
 [15 26]]


In [17]:
a = np.array([[1],[2],[3]])
b = np.array([1,2,3])

print(a.shape)
print(b.shape)

print(a+b)

(3, 1)
(3,)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
# this code gives error

a = np.array([1,2,3,4])
b = np.array([1,2,3])

print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 